scene: cryoet-12262
source_path: data/12262
iterations: 20000
position_lr_init: 0.01
position_lr_final: 0.0005
position_lr_delay_mult: 0.01
position_lr_max_steps: 20000
scaling_lr: 0.001
scaling_lr_init: 0.001
scaling_lr_final: 0.00001
rotation_lr: 0.01
rotation_lr_init: 0.01
rotation_lr_final: 0.0005
intensity_lr: 0.02
intensity_lr_init: 0.02
intensity_lr_final: 0.0005
intensity_lr_delay_mult: 0.01
intensity_lr_max_steps: 20000
lambda_dssim: 0.2
lambda_tv: 0.01
tv_vol_size: 64
percent_dense: 0.005
densification_interval: 600
intensity_reset_interval: 2000
densify_from_iter: 100
densify_until_iter: 10000
densify_grad_threshold: 0.001
intensity_threshold: 0.008
volume_x: 926
volume_y: 958
volume_z: 300
grid_size: 8
sample_ratio: 0.1
image_width: 926
image_height: 958
axis_id: 0
kernel_size: 0.1
extent: 512
num_viewpoints: 8
scale_factor: 1.5
random_init: False
use_anneal: False
use_deform: False
max_gaussians_num: 5000000
eval: False
