scene: shrec_model0
source_path: data/shrec_model0_grand
iterations: 20000
position_lr_init: 0.01
position_lr_final: 0.00001
position_lr_delay_mult: 0.01
position_lr_max_steps: 20000
scaling_lr: 0.01
scaling_lr_init: 0.01
scaling_lr_final: 0.00005
scaling_lr_delay_multi: 0.01
rotation_lr: 0.02
rotation_lr_init: 0.01
rotation_lr_final: 0.00005
rotation_lr_delay_multi: 0.01
intensity_lr: 0.05
intensity_lr_init: 0.05
intensity_lr_final: 0.00005
intensity_lr_delay_mult: 0.01
intensity_lr_max_steps: 20000
lambda_dssim: 0.2
lambda_tv: 0.0
percent_dense: 0.005
densification_interval: 200
intensity_reset_interval: 3000
densify_from_iter: 300
densify_until_iter: 20000
densify_grad_threshold: 0.001
intensity_threshold: 0.01
volume_x: 512
volume_y: 512
volume_z: 180
grid_size: 6
sample_ratio: 0.2
image_width: 512
image_height: 512
axis_id: 0
kernel_size: 0.1
extent: 512
num_viewpoints: 10
scale_factor: 2
random_init: False
use_deform: False
if_align: False
white_background: True